### PR TITLE
Fix ES5 compatibility

### PR DESCRIPTION
**Pull request by Linaco**
Added a pipe in order to babelify the minified version of asyngular-client.
Also referenced this minified version as main in package.json

### CODE REVIEW

**Review by alexandrequillacq — APPROVED** [review]

**Review by na-ji — APPROVED** [review]

**Comment by alexandrequillacq** [comment]
So useful !!!

**Review by KhadijaBenAmmar — APPROVED** [review]

**Comment by jondubois** [comment]
K thanks. Published to npm as v6.2.2.

**Comment by jondubois** [comment]
I had to revert this change because it stopped the client from working on the server-side and also in the browser when not using babel. A lot of people run the client inside node.js or include the file directly in the browser.

I tried to make a separate build output for Babel with extension `.babel.min.js` but I ran into a problem with this: https://github.com/SocketCluster/asyngular-client/pull/2/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R6

Unfortunately, both Node.js and babel use the `main` property to find the entry point for the module. Ideally we need a way to separate the two environments so that they don't break each other. Also I don't want to introduce unnecessary babel dependencies inside a simpler environment which doesn't need them.

If it's not possible to support simple environments AND Babel, we should make a babel-compatible build of this project in a separate repo and publish it to npm as a separate package. IMO Babel has become a completely separate environment at this stage. It's not 'transparent' anymore so why pretend...

**Comment by jondubois** [comment]
IMO, the original intent of Babel was to make developers' lives easier by allowing them to use the latest tech without having to worry about compatibility with the underlying JS engine versions - The goal here was that we (as developers) wouldn't have to worry about upgrading our JS code later (we can use the latest features now). But the irony of it is that I now find myself constantly worrying about babel versions and dependencies. So I don't worry about JS upgrades anymore, but I worry about Babel upgrades instead.

To make matters worse, these days I find Babel upgrades to be more difficult than the actual underlying ECMAScript upgrades which Babel supposedly protect us from. In this project we're using Gulp and so we rely on complex permutations of cross-compatible plugins (and versions) to make the build work; sometimes Gulp plugins are not updated at the same rate as the underlying Babel plugins and this causes problems. When you have so many possible permutations of solutions that can be used to make Babel work, the possible permutations of problems is also huge! Finding the right documentation for any given problem is like finding a needle in a haystack.

**Pull request merged**
